import type { Resource, TerraformFile } from '../types';

export function generateHelmFiles(resources: Resource[]): TerraformFile[] {
  const files: TerraformFile[] = [];

  // 1. Chart.yaml
  const chartYaml = `apiVersion: v2
name: my-infrastructure
description: A Helm chart generated by IaC WebApps
type: application
version: 0.1.0
appVersion: "1.0.0"
`;
  files.push({ filename: 'Chart.yaml', content: chartYaml });

  // 2. values.yaml
  const valuesContent = `# Default values for the chart.
replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

resources: {}
`;
  files.push({ filename: 'values.yaml', content: valuesContent });

  // 3. Templates
  resources.forEach(res => {
    if (res.type === 'kubernetes_deployment') {
       const deployYaml = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${res.name}
  labels:
    app: ${res.name}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ${res.name}
  template:
    metadata:
      labels:
        app: ${res.name}
    spec:
      containers:
        - name: ${res.name}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
`;
       files.push({ filename: `templates/deployment-${res.name}.yaml`, content: deployYaml });
    } else if (res.type === 'kubernetes_service') {
       const svcYaml = `apiVersion: v1
kind: Service
metadata:
  name: ${res.name}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: ${res.properties.app_label || 'my-app'}
`;
       files.push({ filename: `templates/service-${res.name}.yaml`, content: svcYaml });
    }
  });

  // 4. Helpers (standard helm stuff)
  const helpers = `{{/*
Expand the name of the chart.
*/}}
{{- define "my-app.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}
`;
  files.push({ filename: 'templates/_helpers.tpl', content: helpers });

  return files;
}
